defaults:
  - _self_
  - preprocess: default
  - model: crnn_ctc
  - mlflow: local

command:
  name: infer_crnn_ctc

infer:
  checkpoint_path: runs/crnn_ctc/best.pt
  device: cuda
  image_path: data/infer/image.png
